# files are expected to be under config/staches/
# thanks to http://therantsandraves.com/?p=602 for the 'staches

-
  filename: mustache_03.png
  vert_offset: 15
-
  filename: colonel_mustard.png
  vert_offset: 40
  mouth_overlap: 100
-
  filename: mustache_07.png
  vert_offset: 30
  mouth_overlap: 50
